GHA

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -14,17 +14,17 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    - name: Secret
-      env:
-        ENV_FILE: ${{ secrets.ENV_FILE }}
-      # run: echo $ENV_FILE | base64 -d > .env
-      run: |
-        echo $ENV_FILE > env
-        cat env | base64 -di > .env
-    - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag harbor.kafana.dev/ptin/bhfe:test || echo "docker build failed"
-    - name: Push the Docker image
-      run: docker push harbor.kafana.dev/ptin/bhfe:test
+    # - name: Secret
+    #   env:
+    #     ENV_FILE: ${{ secrets.ENV_FILE }}
+    #   # run: echo $ENV_FILE | base64 -d > .env
+    #   run: |
+    #     echo $ENV_FILE > env
+    #     cat env | base64 -di > .env
+    # - name: Build the Docker image
+    #   run: docker build . --file Dockerfile --tag harbor.kafana.dev/ptin/bhfe:test || echo "docker build failed"
+    # - name: Push the Docker image
+    #   run: docker push harbor.kafana.dev/ptin/bhfe:test
     - name: Executing Deploy
       run:  |
         free -m
